name: banking_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # Existing dependencies
  http: ^1.2.2
  shared_preferences: ^2.3.3
  cupertino_icons: ^1.0.8

  # State management
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  provider: ^6.1.1

  # Responsive design
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true

  # Uncomment and modify as needed
  # assets:
  #   - assets/images/
  
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700